### ISSUE TITLE
Add provide key to composer.json

### ISSUE THREAD

**Issue by prudloff-insite** [gggeek/polyfill-xmlrpc#1]
The `composer.json` file should contain something like this:
```json
    "provide": {
        "ext-xmlrpc": "*"
    },
```

This way, if a package requires ext-xmlrpc, the constraint can still be met if this polyfill is installed.

**Comment by gggeek** [comment]
Thx, will add!

**Comment by juherr** [comment]
The goal is the same but [`replace`](https://getcomposer.org/doc/04-schema.md#replace
) is maybe better than [`provide`](https://getcomposer.org/doc/04-schema.md#provide).

**Comment by gggeek** [comment]
@juherr if the extension is enabled, this bundle will not override methods and classes from it. So "provides" is probably better in this case

**Comment by juherr** [comment]
Ok.To be honest, I didn't catch the difference between the 2 options.
Thanks for the clarification.
